### ISSUE TITLE
Use custom memory mapping

### ISSUE THREAD

**Issue by Wlgen** [openhwgroup/force-riscv#42]
Hello, I'm trying to create a series of tests that need to fit in a pretty reduced memory and I am having problems with the layout that force-riscv uses for the exception handlers. The problem is that they overlap with the code section, which has branches (it has loops and condition checking) that are sometimes messed due to this memory being reserved for the exception handlers and its stack. So my question is if there is a good way to force the generator to use a set memory location for the exception handlers (in this case I would like to locate it at the end of the memory region) or, better, to decide what are the memory regions that will correspond to every region that will be generated by force-riscv.

Thanks in advance.

**Comment by noahsherrill** [comment]
None of this has been designed for user configuration at this point, so what I will suggest hasn't been well tested. The `py/riscv/PcConfig.py` contains some functions that allow for configuration of a few memory regions such as the boot region. For the exception handlers specifically, you could try to adjust the values used to initialize `handler_memory_constr` in the `_getHandlerMemoryConstraint()` method within `py/riscv/EnvRISCV.py`.

**Comment by MikeOpenHWGroup** [comment]
Hi @Wlgen, thanks for updating us.  At OpenHW, we strive to maintain a strong discipline for issue tracking, and this means that there should be only one discussion topic per issue.  So if you could:
1. Close this issue since it seems to be resolved (or comment on the issue that it can be closed and we will do it).
2. Open another issue for the address table discussion.

Thanks for your understanding and continued interest in FORCE-RISCV!

**Comment by Wlgen** [comment]
Oh, I'm very sorry, I'll close the issue then, thanks!
